global:
  infraConfigName: subscriber-config
  infraSecretName: subscriber-secret
  podAnnotations: {}
  customLabels: {}
  # INFRA_MODE: cluster, namespace
  INFRA_MODE: "cluster"
# Default values for litmus-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

INFRA_NAME: "helm-infrastructure"
INFRA_DESCRIPTION: "chaos infrastructure deployed with helm"

INFRA_NODE_SELECTOR: ""
SA_EXISTS: true
NS_EXISTS: true
INFRA_TYPE: "external"
# For compatibility with ChaosCenter, Version has to be same
APP_VERSION: "3.8.0"
SKIP_SSL: "true"

# PLATFORM_NAME: AWS, GKE, Openshift, Rancher, Others
PLATFORM_NAME: "Others"

LITMUS_URL: "http://litmus-frontend-service.litmus.svc.cluster.local:9091"
LITMUS_BACKEND_URL: "http://litmus-server-service.litmus.svc.cluster.local:9002"
LITMUS_USERNAME: "admin"
LITMUS_PASSWORD: "litmus"
LITMUS_PROJECT_ID: ""
# -- ID of the litmus environment where the infrastructure will be added
LITMUS_ENVIRONMENT_ID: "sample"

image:
  repository: litmuschaos.docker.scarf.sh/litmuschaos/litmus-helm-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

crds:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

chaos-operator:
  enabled: true

chaos-exporter:
  enabled: true

event-tracker:
  enabled: true

subscriber:
  enabled: true

workflow-controller:
  enabled: true
  crds:
    create: false